export type {
  BusinessBrainEntityKind,
  BusinessBrainEntityRef,
  FactConfidence,
  FactImportance,
  KnowledgeSourceType,
} from "./graph";

export type {
  BrainService,
  BusinessBrain,
  BusinessBrainAggregate,
  BusinessBrainProduct,
  BusinessFact,
  Competitor,
  CreateCompetitorInput,
  CreateCustomerSegmentInput,
  CreateFactInput,
  CreateInternalProcessInput,
  CreateKnowledgeSourceInput,
  CreateProductInput,
  CreateServiceInput,
  CustomerSegment,
  InternalProcess,
  KnowledgeSource,
  UpdateCompetitorInput,
  UpdateCustomerSegmentInput,
  UpdateFactInput,
  UpdateInternalProcessInput,
  UpdateKnowledgeSourceInput,
  UpdateProductInput,
  UpdateServiceInput,
} from "./entities";
