export type {
  MarketingDecisionApprovalMode,
  MarketingDecisionApprovalPolicy,
  MarketingDecisionBudgetConstraint,
  MarketingDecisionBudgetPolicy,
  MarketingDecisionChannelRecommendation,
  MarketingDecisionConstraints,
  MarketingDecisionContentTypeRecommendation,
  MarketingDecisionContextSlices,
  MarketingDecisionCreativeVolume,
  MarketingDecisionCtaStrategy,
  MarketingDecisionEligibility,
  MarketingDecisionEvidence,
  MarketingDecisionEvidenceKind,
  MarketingDecisionPlanActivityRef,
  MarketingDecisionPlanRef,
  MarketingDecisionReadiness,
  MarketingDecisionRecommendationStatus,
  MarketingDecisionRecord,
  MarketingDecisionRequiredDisclaimer,
  MarketingDecisionResponsibilityPolicy,
  MarketingDecisionSource,
  MarketingDecisionStatus,
  MarketingDecisionStrategyRef,
} from "./marketing-decision-record";
